# Generated by Django 5.2.12 on 2026-03-09 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SessionReminder', 'Session Reminder'), ('AppealDeadlineReminder', 'Appeal Deadline Reminder'), ('POAExpiryReminder', 'POA Expiry Reminder'), ('CaseDelayedWarning', 'Case Delayed Warning'), ('InvoiceOverdueAlert', 'Invoice Overdue Alert'), ('General', 'General')], default='General', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_entity_type', models.CharField(blank=True, max_length=100)),
                ('related_entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
