# Generated by Django 5.2.12 on 2026-03-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'فاتورة', 'verbose_name_plural': 'الفواتير'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'دفعة', 'verbose_name_plural': 'المدفوعات'},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'verbose_name': 'سجل وقت', 'verbose_name_plural': 'سجلات الوقت'},
        ),
    ]
