# Generated by Django 5.2.12 on 2026-03-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_invoice_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'verbose_name': 'Time Entry', 'verbose_name_plural': 'Time Entries'},
        ),
    ]
