# Generated by Django 5.2.12 on 2026-03-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_alter_powerofattorney_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='powerofattorney',
            options={'verbose_name': 'Power of Attorney', 'verbose_name_plural': 'Power of Attorneys'},
        ),
    ]
