# Generated by Django 5.2.12 on 2026-03-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'سجل عملية', 'verbose_name_plural': 'سجلات العمليات'},
        ),
    ]
