# Generated by Django 5.2.12 on 2026-03-08 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('CourtJudgment', 'Court Judgment'), ('LegalMemo', 'Legal Memo'), ('Contract', 'Contract'), ('PowerOfAttorney', 'Power Of Attorney'), ('Evidence', 'Evidence'), ('ExpertReport', 'Expert Report'), ('PaymentReceipt', 'Payment Receipt'), ('ClientDocument', 'Client Document'), ('Other', 'Other')], default='Other', max_length=40)),
                ('file', models.FileField(upload_to='case_documents/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_confidential', models.BooleanField(default=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
