# Generated by Django 5.2.12 on 2026-03-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rename_uploaded_at_document_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'مستند', 'verbose_name_plural': 'المستندات'},
        ),
    ]
