# Generated by Django 5.2.12 on 2026-03-08 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('case_type', models.CharField(choices=[('Commercial', 'Commercial'), ('Civil', 'Civil'), ('Criminal', 'Criminal'), ('Labor', 'Labor'), ('Family', 'Family'), ('RealEstate', 'Real Estate'), ('Enforcement', 'Enforcement'), ('Administrative', 'Administrative'), ('Other', 'Other')], default='Other', max_length=30)),
                ('court_name', models.CharField(max_length=255)),
                ('court_circuit', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('New', 'New'), ('InProgress', 'In Progress'), ('WaitingCourtSession', 'Waiting Court Session'), ('WaitingJudgment', 'Waiting Judgment'), ('JudgmentIssued', 'Judgment Issued'), ('UnderAppeal', 'Under Appeal'), ('InEnforcement', 'In Enforcement'), ('Suspended', 'Suspended'), ('Closed', 'Closed')], default='New', max_length=30)),
                ('priority', models.CharField(choices=[('Urgent', 'Urgent'), ('Important', 'Important'), ('Normal', 'Normal')], default='Normal', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_lawyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='clients.client')),
                ('power_of_attorney', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='clients.powerofattorney')),
            ],
        ),
        migrations.CreateModel(
            name='CaseAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_from', models.DateTimeField()),
                ('assigned_to', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='cases.case')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_assignment_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CourtSession', 'Court Session'), ('AppealDeadline', 'Appeal Deadline'), ('ExpertVisit', 'Expert Visit'), ('ClientMeeting', 'Client Meeting'), ('InternalReview', 'Internal Review'), ('DocumentSubmission', 'Document Submission'), ('PaymentDeadline', 'Payment Deadline'), ('JudgmentIssued', 'Judgment Issued'), ('EnforcementAction', 'Enforcement Action'), ('Other', 'Other')], default='Other', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_case_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
