# Generated by Django 5.2.12 on 2026-03-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'قضية', 'verbose_name_plural': 'القضايا'},
        ),
        migrations.AlterModelOptions(
            name='caseassignmenthistory',
            options={'verbose_name': 'سجل توزيع قضية', 'verbose_name_plural': 'سجلات توزيع القضايا'},
        ),
        migrations.AlterModelOptions(
            name='caseevent',
            options={'verbose_name': 'حدث قضية', 'verbose_name_plural': 'أحداث القضايا'},
        ),
    ]
