# Generated by Django 5.2.12 on 2026-03-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_case_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Case', 'verbose_name_plural': 'Cases'},
        ),
        migrations.AlterModelOptions(
            name='caseassignmenthistory',
            options={'verbose_name': 'Case Assignment History', 'verbose_name_plural': 'Case Assignment Histories'},
        ),
        migrations.AlterModelOptions(
            name='caseevent',
            options={'verbose_name': 'Case Event', 'verbose_name_plural': 'Case Events'},
        ),
    ]
